spring:
  application:
    name: gateway-service
  config:
    import:
      - nacos:gateway-service-dev.yml
      - nacos:common-dev.yml
      - nacos:auth-dev.yml
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
      config:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        file-extension: yml

knife4j:
  # 聚合swagger文档
  gateway:
    # 生产环境上线时，配置文件通过配置 knife4j.gateway.enabled: false 进行关闭,避免接口泄漏，造成安全问题
    enabled: true
    # 排序规则(tag/operation排序自4.2.0版本新增)
    # 取值：alpha-默认排序规则，官方swagger-ui默认实现,order-Knife4j提供的增强排序规则，开发者可扩展x-order，根据数值来自定义排序
    tags-sorter: order
    operations-sorter: order
    # 指定手动配置的模式(默认为该模式)
    strategy: manual
    routes:
      - name: 管理服务
        # 真实子服务访问url地址-提供OpenAPI的文档
        url: /admin-service/v3/api-docs?group=管理模块
        service-name: admin-service
        # 路由前缀
        # 兼容OpenAPI3规范在聚合时丢失contextPath属性的异常情况，由开发者自己配置contextPath,Knife4j的前端Ui做兼容处理,与url属性独立不冲突，仅OpenAPI3规范聚合需要，OpenAPI2规范不需要设置此属性,默认为(apiPathPrefix)
        context-path: /
        order: 2
