spring:
  application:
    name: gateway-service
  config:
    import:
      - nacos:gateway-service-dev.yml
      - nacos:common-db-dev.yml
      - nacos:common-redis-dev.yml
      - nacos:common-jwt-dev.yml
      - nacos:common-secure-dev.yml
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
      config:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        file-extension: yml