spring:
  application:
    name: fee-service
  config:
    import:
      - nacos:fee-service-dev.yml
      - nacos:common-db-dev.yml
      - nacos:common-redis-dev.yml
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
      config:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        file-extension: yml