secure:
  whitelist:
    login-url: /api/auth/login
    logout-url: /api/auth/logout
    urls:
      - /application/auth/**
      - /doc.html
      - /webjars/**
      - /v3/**
      - /swagger-resources/**
