secure:
  whitelist:
    login-url: /api/auth/login
    logout-url: /api/auth/logout
    urls:
      - /auth/**
      - /doc.html
      - /webjars/**
      - /v3/** # 放行网关的swagger
      - /*/v3/** # 放行每个子模块的swagger
      - /swagger-resources/**
      - /favicon.ico
