spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    # druid 连接池管理
    druid:
      # 多数据源配置
      datasource1:
        name: datasource1
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/demo?currentSchema=public
        username: postgres
        password: 123456
      datasource2:
        name: datasource2
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/demo?currentSchema=sys
        username: postgres
        password: 123456
      datasource3:
        name: datasource3
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/demo?currentSchema=basic
        username: postgres
        password: 123456
      datasource4:
        name: datasource4
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/demo?currentSchema=order
        username: postgres
        password: 123456
      datasource5:
        name: datasource5
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/demo?currentSchema=stock
        username: postgres
        password: 123456
      # 初始化时建立物理连接的个数
      initial-size: 5
      # 连接池的最小空闲数量
      min-idle: 5
      # 连接池最大连接数量
      max-active: 20
      # 获取连接时最大等待时间，单位毫秒
      max-wait: 60000
      # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
      # 既作为检测的间隔时间又作为testWhileIdel执行的依据
      time-between-eviction-runs-millis: 60000
      # 销毁线程时检测当前连接的最后活动时间和当前时间差大于该值时，关闭当前连接(配置连接在池中的最小生存时间)
      min-evictable-idle-time-millis: 30000
      # 用来检测数据库连接是否有效的sql 必须是一个查询语句(oracle中为 select 1 from dual)
      validation-query: select 1
      # 申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-borrow: false
      # 归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-return: false
      # 是否缓存preparedStatement, 也就是PSCache,PSCache对支持游标的数据库性能提升巨大，比如说oracle,在mysql下建议关闭。
      pool-prepared-statements: false
      # 置监控统计拦截的filters，去掉后监控界面sql无法统计，stat: 监控统计、Slf4j:日志记录、waLL: 防御sqL注入
      filters: stat,wall,slf4j
      # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
      max-pool-prepared-statement-per-connection-size: -1
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

      web-stat-filter:
        # 是否启用StatFilter默认值true
        enabled: true
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤的格式
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.png,*.css,*.ico

      stat-view-servlet:
        # 是否启用StatViewServlet默认值true
        enabled: true
        # 访问路径为/druid时，跳转到StatViewServlet
        url-pattern: /druid/*
        # 是否能够重置数据
        reset-enable: false
        # 需要账号密码才能访问控制台，默认为root
        login-username: druid
        login-password: druid
        # IP白名单
        allow: 127.0.0.1
        # IP黑名单（共同存在时，deny优先于allow）
        deny:

---
mybatis-plus:
  # 指定mapper配置文件路径
  mapper-locations: classpath*:/mapper/**.xml
  # 指定实体包
  type-aliases-package: com.italycalibur.ciallo.common.models.entity
  # 指定父类
  type-aliases-super-type: com.italycalibur.ciallo.common.domain.BaseEntity
  # 全局设置
  global-config:
    # 禁用打印banner
    banner: false
    # 数据库策略
    db-config:
      # 表名前缀
      table-prefix: t_
      # 主键策略
      id-type: ASSIGN_ID