server:
  port: 9999
  servlet:
    encoding:
      force: true
      charset: UTF-8
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:9085
          jwk-set-uri: http://127.0.0.1:9085/oauth2/jwks
      client:
        provider:
          oauth-server:
            issuer-uri: http://127.0.0.1:9085
            user-info-uri: ${spring.security.oauth2.client.provider.oauth-server.issuer-uri}/user
            authorization-uri: ${spring.security.oauth2.client.provider.oauth-server.issuer-uri}/oauth2/authorize
            token-uri: ${spring.security.oauth2.client.provider.oauth-server.issuer-uri}/oauth2/token
        registration:
          messageing-client-oidc:
            provider: oauth-server
            client-id: messageing-client
            client-secret: secret
            client-name: messageing-client-oidc
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:9999/login/oauth2/code/{registrationId}
            scope:
              - profile
              - openid
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
      filter:
        enabled: false
    gateway:
      discovery:
        locator:
          # 开启注册中心路由功能
          enabled: true
          # 将请求路径上的服务名配置为小写
          lower-case-service-id: true
      default-filters:
        - TokenRelay=
      routes:
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/admin/**,/auth/**
          filters:
            - PrefixPath=/application
        - id: basic-service
          uri: lb://basic-service
          predicates:
            - Path=/basic/**
          filters:
            - PrefixPath=/application
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
          filters:
            - PrefixPath=/application
        - id: stock-service
          uri: lb://stock-service
          predicates:
            - Path=/stock/**
          filters:
            - PrefixPath=/application
        - id: fee-service
          uri: lb://fee-service
          predicates:
            - Path=/fee/**
          filters:
            - PrefixPath=/application
config:
  info: 前辈，Ciallo～(∠・ω< )⌒★
  gateway:
    enabled: true