server:
  port: 9999
  servlet:
    encoding:
      force: true
      charset: UTF-8
spring:
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
      filter:
        enabled: false
    gateway:
      globalcors:
        cors-configuration:
          '[/**]':
            allowedOrigins: '[*]'
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      discovery:
        locator:
          # 开启注册中心路由功能
          enabled: true
          # 将请求路径上的服务名配置为小写
          lower-case-service-id: true
      routes:
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/admin/**,/auth/**
        - id: basic-service
          uri: lb://basic-service
          predicates:
            - Path=/basic/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
        - id: stock-service
          uri: lb://stock-service
          predicates:
            - Path=/stock/**
        - id: fee-service
          uri: lb://fee-service
          predicates:
            - Path=/fee/**
config:
  info: 前辈，Ciallo～(∠・ω< )⌒★