metadata:
- appName: ''
  dataId: admin-service-dev.yml
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: basic-service-dev.yml
  desc: ''
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: common-db-dev.yml
  desc: ''
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: gateway-service-dev.yml
  desc: ''
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: common-jwt-dev.yml
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: common-redis-dev.yml
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: common-secure-dev.yml
  desc: ''
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: order-service-dev.yml
  desc: ''
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: stock-service-dev.yml
  desc: ''
  group: DEFAULT_GROUP
  type: yaml
