spring:
  application:
    name: auth-service
  config:
    import:
      - nacos:auth-service-dev.yml
      - nacos:common-dev.yml
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
      config:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        file-extension: yml