spring:
  application:
    name: admin-service
  config:
    import:
      - nacos:admin-service-dev.yml
      - nacos:common-dev.yml
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
      config:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        file-extension: yml
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: '管理模块'
      paths-to-match: '/**'
      packages-to-scan: com.italycalibur.ciallo.admin
# knife4j的增强配置，不需要增强可以不配
knife4j:
  # 开启增强配置
  enable: true
  # 开启生产环境屏蔽
  production: false
  setting:
    language: zh_cn
    swagger-model-name: 实体类列表
    enable-version: true # 是否开启界面中对某接口的版本控制,如果开启，后端变化后Ui界面会存在小蓝点
    enable-filter-multipart-apis: true # RequestMapping接口,是否开启过滤
    enable-filter-multipart-api-method-type: GET # RequestMapping只展示哪种类型
    enable-home-custom: true # 开启自定义主页
    home-custom-path: classpath:markdown/home.md # 自定义主页路径
    enable-footer-custom: true # 开启自定义页脚
    footer-custom-content: <strong>MIT License | Copyright  2025 - [italycalibur2019](https://github.com/italycalibur2019)</strong>