spring:
  application:
    name: admin-service
  config:
    import:
      - nacos:admin-service-dev.yml
      - nacos:common-db-dev.yml
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
      config:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        file-extension: yml