server:
  port: 8090
spring:
  application:
    name: Spring-Cloud-Alibaba-Demo-Admin
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos