server:
  port: 8091
spring:
  application:
    name: Spring-Cloud-Alibaba-Demo-Basic
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos